version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: jwt-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jwt_auth_starter
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/01_init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d jwt_auth_starter"]
      interval: 5s
      timeout: 3s
      retries: 10

  backend:
    build: ./backend
    container_name: jwt-backend
    restart: unless-stopped
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/jwt_auth_starter
      JWT_SECRET: change_me
      PORT: 4000
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "4000:4000"

  frontend:
    build: ./frontend
    container_name: jwt-frontend
    restart: unless-stopped
    environment:
      VITE_API_BASE: http://localhost:4000
    depends_on:
      - backend
    ports:
      - "5173:5173"

volumes:
  pgdata: {}
